# Generated by Django 6.0.4 on 2026-06-29 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canteens', '0005_create_transit_warehouses'),
        ('core', '0007_add_is_readonly_to_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BufetImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Název souboru')),
                ('export_date', models.DateField(blank=True, help_text='Datum vygenerování přehledu (z názvu souboru)', null=True, verbose_name='Datum exportu')),
                ('status', models.CharField(choices=[('DRAFT', 'Náhled'), ('CONFIRMED', 'Potvrzeno')], default='DRAFT', max_length=10, verbose_name='Stav')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámky')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('write_off_id', models.IntegerField(blank=True, help_text='ID záznamu StockWriteOff vytvořeného při potvrzení importu', null=True, verbose_name='ID odepsání')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bufet_imports', to='canteens.warehouse', verbose_name='Sklad')),
            ],
            options={
                'verbose_name': 'Import bufetu',
                'verbose_name_plural': 'Importy bufetu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BufetImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(max_length=50, verbose_name='Kód artiklíku')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='EAN kód')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('group', models.CharField(blank=True, max_length=100, verbose_name='Skupina')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prodané množství')),
                ('unit', models.CharField(default='ks', max_length=20, verbose_name='MJ')),
                ('total_price_with_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tržba s DPH')),
                ('total_price_without_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tržba bez DPH')),
                ('establishments', models.CharField(blank=True, help_text='Provozovny, kde bylo zboží prodáno (oddělené čárkou)', max_length=500, verbose_name='Provozovny')),
                ('skip', models.BooleanField(default=False, help_text='Tato položka nebude odepsána ze skladu', verbose_name='Přeskočit')),
                ('bufet_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bufet.bufetimport', verbose_name='Import')),
                ('ingredient', models.ForeignKey(blank=True, help_text='Spárovaná surovina ve skladu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ingredient', verbose_name='Surovina')),
            ],
            options={
                'verbose_name': 'Položka importu bufetu',
                'verbose_name_plural': 'Položky importu bufetu',
                'ordering': ['name'],
            },
        ),
    ]
