# Generated by Django 6.0.4 on 2026-07-01 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bufet', '0001_initial'),
        ('inventory', '0022_write_off_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bufetimport',
            name='write_off_id',
        ),
        migrations.AddField(
            model_name='bufetimport',
            name='write_off',
            field=models.ForeignKey(blank=True, help_text='Záznam StockWriteOff vytvořený při potvrzení importu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bufet_imports', to='inventory.stockwriteoff', verbose_name='Odepsání ze skladu'),
        ),
    ]
