# Generated by Django 6.0.4 on 2026-07-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bufet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bufetimportitem',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='bufetimportitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='bufetimportitem',
            name='total_price_with_vat',
        ),
        migrations.RemoveField(
            model_name='bufetimportitem',
            name='total_price_without_vat',
        ),
    ]
