# Generated by Django 5.2.6 on 2025-09-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canteens', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions_adult', models.PositiveIntegerField(verbose_name='Počet dospělých porcí')),
                ('portions_child', models.PositiveIntegerField(verbose_name='Počet dětských porcí')),
                ('date', models.DateField(verbose_name='Datum vaření')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canteens.canteen', verbose_name='Jídelna')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.recipe', verbose_name='Recept')),
            ],
            options={
                'verbose_name': 'Výrobní příkaz',
                'verbose_name_plural': 'Výrobní příkazy',
            },
        ),
        migrations.CreateModel(
            name='PickingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Plánované množství')),
                ('quantity_actual', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Skutečně vydané množství')),
                ('status', models.CharField(choices=[('PENDING', 'Čeká na vydání'), ('COMPLETED', 'Vydáno')], default='PENDING', max_length=10, verbose_name='Stav')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ingredient', verbose_name='Surovina')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_list_items', to='production.productionorder', verbose_name='Výrobní příkaz')),
            ],
            options={
                'verbose_name': 'Položka výdejky',
                'verbose_name_plural': 'Položky výdejky',
                'unique_together': {('production_order', 'ingredient')},
            },
        ),
    ]
