# Generated by Django 5.2.6 on 2025-09-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickinglist',
            name='warehouse',
            field=models.ForeignKey(help_text='Sklad, ze kterého se má surovina vydat.', null=True, on_delete=django.db.models.deletion.PROTECT, to='canteens.warehouse', verbose_name='Sklad'),
        ),
    ]
