# Generated by Django 4.2.24 on 2025-09-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0001_initial'),
        ('production', '0002_pickinglist_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název jídelníčku')),
                ('date_from', models.DateField(verbose_name='Datum od')),
                ('date_to', models.DateField(verbose_name='Datum do')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('default_portions_adult', models.PositiveIntegerField(default=50, verbose_name='Výchozí počet dospělých porcí')),
                ('default_portions_child', models.PositiveIntegerField(default=30, verbose_name='Výchozí počet dětských porcí')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canteens.canteen', verbose_name='Jídelna')),
            ],
            options={
                'verbose_name': 'Jídelníček',
                'verbose_name_plural': 'Jídelníčky',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='menu_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='production.menuplan', verbose_name='Jídelníček'),
        ),
    ]
