# Generated by Django 4.2.25 on 2025-10-27 20:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_menuplan_productionorder_menu_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='portion_coefficient',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Koeficient velikosti porce (1.0 = normální, 0.5 = poloviční, 1.5 = větší)', max_digits=5, verbose_name='Koeficient porce'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='portions_adult',
            field=models.PositiveIntegerField(default=0, verbose_name='Počet dospělých porcí'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='portions_child',
            field=models.PositiveIntegerField(default=0, verbose_name='Počet dětských porcí'),
        ),
    ]
