# Generated by Django 4.2.25 on 2025-10-27 21:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionorder_portion_coefficient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPlanCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Např. 'Normální porce', 'Malá porce', 'Velká porce'", max_length=100, verbose_name='Název')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Např. 1.0 = normální, 0.5 = poloviční, 1.5 = větší', max_digits=5, verbose_name='Koeficient')),
                ('order', models.PositiveIntegerField(default=0, help_text='Pořadí zobrazení (nižší číslo = dříve)', verbose_name='Pořadí')),
                ('menu_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_coefficients', to='production.menuplan', verbose_name='Jídelníček')),
            ],
            options={
                'verbose_name': 'Výchozí koeficient',
                'verbose_name_plural': 'Výchozí koeficienty',
                'ordering': ['menu_plan', 'order'],
            },
        ),
    ]
