# Generated by Django 4.2.25 on 2025-10-27 22:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_menuplancoefficient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderPortionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Např. 1.0 = normální, 0.75 = menší', max_digits=5, verbose_name='Koeficient')),
                ('portions', models.PositiveIntegerField(help_text='Kolik porcí s tímto koeficientem', verbose_name='Počet porcí')),
                ('order', models.PositiveIntegerField(default=0, help_text='Pořadí zobrazení', verbose_name='Pořadí')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portion_variants', to='production.productionorder', verbose_name='Výrobní příkaz')),
            ],
            options={
                'verbose_name': 'Varianta porce',
                'verbose_name_plural': 'Varianty porcí',
                'ordering': ['production_order', 'order'],
            },
        ),
    ]
