# Generated by Django 4.2.24 on 2025-11-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0001_initial'),
        ('production', '0006_productionorderportionvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='canteens.canteen', verbose_name='Jídelna'),
        ),
    ]
