# Generated by Django 4.2.24 on 2025-11-14 12:16

from django.db import migrations
from datetime import timedelta


def migrate_orphan_orders_to_menu_plans(apps, schema_editor):
    """
    Najde všechny ProductionOrder bez menu_plan a vytvoří pro ně jednorázové jídelníčky.
    Seskupí je podle jídelny a data, aby minimalizoval počet vytvořených jídelníčků.

    DŮLEŽITÉ: Záznamy bez canteen_id NEMOHOU být migrovány a způsobí selhání migrace.
    Před spuštěním této migrace zajistěte, že všechny ProductionOrder mají přiřazenu jídelnu.

    Zpracování záznamů:
    - Záznamy S canteen_id: Budou migrovány do nově vytvořených MenuPlan
    - Záznamy BEZ canteen_id: Migrace selže s chybou a vypíše IDs k ručnímu zpracování

    Ruční zpracování problémových záznamů:
    1. python manage.py shell
    2. from apps.production.models import ProductionOrder
    3. order = ProductionOrder.objects.get(id=<ID>)
    4. order.canteen = <správná jídelna>
    5. order.save()
    """
    ProductionOrder = apps.get_model('production', 'ProductionOrder')
    MenuPlan = apps.get_model('production', 'MenuPlan')

    # Najdeme všechny příkazy bez menu_plan
    orphan_qs = ProductionOrder.objects.filter(menu_plan__isnull=True)
    
    if not orphan_qs.exists():
        return

    # Ověříme že všechny mají canteen_id
    missing_canteen_ids = list(orphan_qs.filter(canteen__isnull=True).values_list('id', flat=True))
    
    if missing_canteen_ids:
        print("="*80)
        print(f"⚠️  VAROVÁNÍ: Celkem {len(missing_canteen_ids)} výrobních příkazů bez canteen_id nebylo migrováno!")
        print("   Tyto záznamy MUSÍ být zpracovány ručně před migrací 0009!")
        print(f"   ProductionOrder IDs: {missing_canteen_ids}")
        print("   Akce k provedení:")
        print("   1. Přiřaďte těmto záznamům canteen pomocí Django admin nebo shell")
        print("   2. Nebo je smažte, pokud jsou nevalidní")
        print("   3. Poté znovu spusťte migraci")
        print("="*80)
        
        raise ValueError(
            f"Migrace přerušena: {len(missing_canteen_ids)} ProductionOrder nemá canteen_id. "
            f"Tyto záznamy musí být opraveny před pokračováním. IDs: {missing_canteen_ids}"
        )

    # Seskupíme podle jídelny a data na úrovni databáze
    groups = orphan_qs.exclude(canteen__isnull=True)\
                      .values('canteen_id', 'date')\
                      .distinct()

    # Vytvoříme jídelníčky a přiřadíme příkazy pomocí bulk update
    created_count = 0
    for grp in groups:
        # Vytvoříme jednorázový jídelníček pro tento den
        menu_plan = MenuPlan.objects.create(
            name=f"Migrovaný jídelníček - {grp['date'].strftime('%d.%m.%Y')}",
            canteen_id=grp['canteen_id'],
            date_from=grp['date'],
            date_to=grp['date'],
            default_portions_adult=50,
            default_portions_child=0
        )
        
        # Jeden SQL UPDATE pro celou skupinu místo N save()
        ProductionOrder.objects.filter(
            menu_plan__isnull=True,
            canteen_id=grp['canteen_id'],
            date=grp['date']
        ).update(menu_plan=menu_plan)
        
        created_count += 1

    total_migrated = orphan_qs.count()
    print(f"Migrace dokončena: vytvořeno {created_count} jídelníčků pro {total_migrated} výrobních příkazů")
def reverse_migration(apps, schema_editor):
    """
    Reverse operace - odstraní menu_plan z migrovaných příkazů.
    Poznámka: Toto nesmaže vytvořené jídelníčky, pouze je odpojí.
    """
    ProductionOrder = apps.get_model('production', 'ProductionOrder')
    MenuPlan = apps.get_model('production', 'MenuPlan')
    
    # Najdeme jídelníčky vytvořené migrací
    migrated_menus = MenuPlan.objects.filter(name__startswith="Migrovaný jídelníček -")
    
    # Odpojíme příkazy od těchto jídelníčků
    ProductionOrder.objects.filter(menu_plan__in=migrated_menus).update(menu_plan=None)
    
    # Smažeme vytvořené jídelníčky
    migrated_menus.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_make_canteen_nullable'),
    ]

    operations = [
        migrations.RunPython(migrate_orphan_orders_to_menu_plans, reverse_migration),
    ]
