# Generated by Django 4.2.24 on 2025-11-14 12:16

from django.db import migrations
from datetime import timedelta


def migrate_orphan_orders_to_menu_plans(apps, schema_editor):
    """
    Najde všechny ProductionOrder bez menu_plan a vytvoří pro ně jednorázové jídelníčky.
    Seskupí je podle jídelny a data, aby minimalizoval počet vytvořených jídelníčků.
    """
    ProductionOrder = apps.get_model('production', 'ProductionOrder')
    MenuPlan = apps.get_model('production', 'MenuPlan')
    
    # Najdeme všechny příkazy bez menu_plan
    orphan_orders = ProductionOrder.objects.filter(menu_plan__isnull=True)
    
    if not orphan_orders.exists():
        return
    
    # Seskupíme podle jídelny a data
    orders_by_canteen_date = {}
    for order in orphan_orders:
        # Pokud order nemá canteen, zkusíme ho získat jinak
        if not order.canteen_id:
            continue
            
        key = (order.canteen_id, order.date)
        if key not in orders_by_canteen_date:
            orders_by_canteen_date[key] = []
        orders_by_canteen_date[key].append(order)
    
    # Vytvoříme jídelníčky pro každou kombinaci jídelna+datum
    for (canteen_id, date), orders in orders_by_canteen_date.items():
        # Vytvoříme jednorázový jídelníček pro tento den
        menu_plan = MenuPlan.objects.create(
            name=f"Migrovaný jídelníček - {date.strftime('%d.%m.%Y')}",
            canteen_id=canteen_id,
            date_from=date,
            date_to=date,
            default_portions_adult=50,
            default_portions_child=0
        )
        
        # Přiřadíme všechny příkazy k tomuto jídelníčku
        for order in orders:
            order.menu_plan = menu_plan
            order.save(update_fields=['menu_plan'])
    
    print(f"Migrace dokončena: vytvořeno {len(orders_by_canteen_date)} jídelníčků pro {orphan_orders.count()} výrobních příkazů")


def reverse_migration(apps, schema_editor):
    """
    Reverse operace - odstraní menu_plan z migrovaných příkazů.
    Poznámka: Toto nesmaže vytvořené jídelníčky, pouze je odpojí.
    """
    ProductionOrder = apps.get_model('production', 'ProductionOrder')
    MenuPlan = apps.get_model('production', 'MenuPlan')
    
    # Najdeme jídelníčky vytvořené migrací
    migrated_menus = MenuPlan.objects.filter(name__startswith="Migrovaný jídelníček -")
    
    # Odpojíme příkazy od těchto jídelníčků
    ProductionOrder.objects.filter(menu_plan__in=migrated_menus).update(menu_plan=None)
    
    # Smažeme vytvořené jídelníčky
    migrated_menus.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_make_canteen_nullable'),
    ]

    operations = [
        migrations.RunPython(migrate_orphan_orders_to_menu_plans, reverse_migration),
    ]
