# Generated by Django 4.2.24 on 2025-11-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Nastaví menu_plan jako povinné pole.
    Předpokládá že migrace 0008 již přiřadila všem příkazům menu_plan.
    """

    dependencies = [
        ('production', '0008_migrate_orders_to_menu_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='menu_plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='production_orders', 
                to='production.menuplan', 
                verbose_name='Jídelníček'
            ),
        ),
    ]
