# Generated by Django 4.2.24 on 2025-11-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_make_menu_plan_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='portion_coefficient',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='portions_adult',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='portions_child',
        ),
    ]
