# Generated by Django 4.2.24 on 2025-11-18 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canteens', '0001_initial'),
        ('production', '0010_remove_deprecated_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingListDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název výdejky')),
                ('date_from', models.DateField(verbose_name='Datum od')),
                ('date_to', models.DateField(verbose_name='Datum do')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canteens.canteen', verbose_name='Jídelna')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Dokument výdejky',
                'verbose_name_plural': 'Dokumenty výdejek',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pickinglist',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.pickinglistdocument', verbose_name='Dokument výdejky'),
        ),
    ]
