# Generated by Django 4.2.25 on 2025-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_pickinglistdocument_pickinglist_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickinglistdocument',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archivováno'),
        ),
        migrations.AddField(
            model_name='pickinglistdocument',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivováno dne'),
        ),
    ]
