# Generated by Django 5.2.6 on 2025-11-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_pickinglistdocument_pickinglist_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickinglistdocument',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archivováno'),
        ),
    ]
