# Generated by Django 6.0.1 on 2026-01-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_pickinglistdocument_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název šablony')),
                ('description', models.TextField(blank=True, help_text='Stručný popis šablony a co obsahuje', verbose_name='Popis')),
                ('xml_content', models.TextField(help_text='XML definice receptů a harmonogramu', verbose_name='XML obsah')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
            ],
            options={
                'verbose_name': 'Šablona jídelníčku',
                'verbose_name_plural': 'Šablony jídelníčků',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('BREAKFAST', 'Snídaně'), ('SNACK_MORNING', 'Svačina dopolední'), ('LUNCH', 'Oběd'), ('SNACK_AFTERNOON', 'Svačina odpolední'), ('DINNER', 'Večeře')], db_index=True, default='LUNCH', help_text='Kategorie jídla (snídaně, oběd, večeře, svačina)', max_length=20, verbose_name='Typ jídla'),
        ),
    ]
