# Generated by Django 6.0.1 on 2026-01-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_menutemplate_productionorder_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderportionvariant',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Např. Vedoucí, Děti, Normální porce', max_length=100, verbose_name='Název varianty'),
        ),
    ]
