# Generated by Django 6.0.1 on 2026-01-19 15:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_productionorderportionvariant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='selling_vat_rate',
            field=models.DecimalField(choices=[(Decimal('21'), '21%'), (Decimal('12'), '12%'), (Decimal('0'), '0%')], decimal_places=2, default=Decimal('12.00'), help_text='DPH sazba pro prodej tohoto jídla (zkopíruje se z receptu při vytvoření)', max_digits=5, verbose_name='Sazba DPH při prodeji (%)'),
        ),
    ]
