# Generated by Django 6.0.1 on 2026-01-16 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0003_warehouse_locked_by_inventory'),
        ('core', '0004_alter_recipe_category_alter_recipe_code'),
        ('production', '0014_productionorderportionvariant_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('is_shared', models.BooleanField(db_index=True, default=False, help_text='Sdílený preset je viditelný pro všechny uživatele', verbose_name='Sdílený')),
                ('coefficients', models.JSONField(help_text='JSON pole s objekty {name, coefficient, portions, order}', verbose_name='Koeficienty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
            ],
            options={
                'verbose_name': 'Preset koeficientů',
                'verbose_name_plural': 'Presety koeficientů',
                'ordering': ['-is_shared', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['menu_plan', 'date'], name='production__menu_pl_e1e475_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['date', 'meal_type'], name='production__date_aa0938_idx'),
        ),
        migrations.AddField(
            model_name='coefficientpreset',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Vlastník presetu (null = systémový preset)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vlastník'),
        ),
        migrations.AlterUniqueTogether(
            name='coefficientpreset',
            unique_together={('user', 'name')},
        ),
    ]
