# Generated by Django 6.0.1 on 2026-01-21 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_selling_vat_rate'),
        ('production', '0015_productionorder_selling_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickinglist',
            name='is_customized',
            field=models.BooleanField(default=False, help_text='Označuje, že tato výdejka patří k upravenému jídlu', verbose_name='Je upraveno'),
        ),
        migrations.CreateModel(
            name='ProductionOrderRecipeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customized', models.BooleanField(default=False, help_text='Označuje, že tento výrobní příkaz má upravené ingredience', verbose_name='Je upraveno')),
                ('customization_note', models.TextField(blank=True, help_text='Důvod nebo popis úpravy receptu', verbose_name='Poznámka k úpravě')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('production_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_override', to='production.productionorder', verbose_name='Výrobní příkaz')),
            ],
            options={
                'verbose_name': 'Override receptu',
                'verbose_name_plural': 'Override receptů',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderIngredientOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_portion', models.DecimalField(blank=True, decimal_places=3, help_text='Přepsané množství na 1 porci. NULL = odstraněno z receptu', max_digits=10, null=True, verbose_name='Množství na porci (g)')),
                ('original_quantity', models.DecimalField(decimal_places=3, help_text='Původní množství z receptu pro referenci', max_digits=10, verbose_name='Původní množství (g)')),
                ('is_added', models.BooleanField(default=False, help_text='Ingredience přidaná navíc (nebyla v původním receptu)', verbose_name='Přidáno')),
                ('is_removed', models.BooleanField(default=False, help_text='Ingredience odstraněná z receptu', verbose_name='Odstraněno')),
                ('notes', models.CharField(blank=True, help_text='Poznámka k této úpravě', max_length=200, verbose_name='Poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ingredient', verbose_name='Surovina')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_overrides', to='production.productionorder', verbose_name='Výrobní příkaz')),
            ],
            options={
                'verbose_name': 'Override ingredience',
                'verbose_name_plural': 'Override ingrediencí',
                'unique_together': {('production_order', 'ingredient')},
            },
        ),
    ]
