# Generated by Django 6.0.1 on 2026-03-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_pickinglist_is_customized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuplancoefficient',
            name='default_portions',
            field=models.PositiveIntegerField(default=50, help_text='Výchozí počet porcí pro tuto variantu při přidávání jídel', verbose_name='Výchozí počet porcí'),
        ),
    ]
