# Generated by Django 6.0.4 on 2026-06-10 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_menuplancoefficient_default_portions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickinglistdocument',
            name='cook',
            field=models.ForeignKey(blank=True, help_text='Kuchař, který připravoval jídlo v tomto období', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooked_picking_lists', to=settings.AUTH_USER_MODEL, verbose_name='Kuchař'),
        ),
    ]
