# Generated by Django 6.0.4 on 2026-06-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_make_production_order_nullable_in_pickinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickinglistdocument',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Pre-vygenerovaný PDF soubor výdejky', null=True, upload_to='picking_lists/pdf/', verbose_name='PDF soubor'),
        ),
        migrations.AddField(
            model_name='pickinglistdocument',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, help_text='Časová značka posledního vygenerování PDF', null=True, verbose_name='PDF vygenerováno'),
        ),
    ]
