# Generated by Django 6.0.4 on 2026-07-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0005_create_transit_warehouses'),
        ('core', '0010_alter_ingredient_options'),
        ('production', '0021_alter_productionorder_meal_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(condition=models.Q(('meal_type', 'DINNER_SECOND')), fields=('canteen', 'date', 'meal_type'), name='unique_second_dinner_per_canteen_day'),
        ),
    ]
