# Generated by Django 6.0.4 on 2026-07-11 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_productionorder_unique_second_dinner_per_canteen_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='replacement_of',
            field=models.ForeignKey(blank=True, help_text='Původní plánované jídlo, které tento příkaz ve výdejce nahrazuje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='production.productionorder', verbose_name='Záměna za jídlo'),
        ),
    ]
