# Generated by Django 6.0.4 on 2026-07-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0005_create_transit_warehouses'),
        ('core', '0010_alter_ingredient_options'),
        ('production', '0023_productionorder_replacement_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('BREAKFAST', 'Snídaně'), ('SNACK_MORNING', 'Svačina dopolední'), ('SOUP', 'Polévka'), ('LUNCH', 'Oběd'), ('SNACK_AFTERNOON', 'Svačina odpolední'), ('DINNER', 'Večeře'), ('DINNER_SECOND', 'Druhá večeře')], db_index=True, default='LUNCH', help_text='Kategorie jídla (snídaně, oběd, večeře, svačina)', max_length=20, verbose_name='Typ jídla'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(condition=models.Q(('meal_type', 'SOUP')), fields=('canteen', 'date', 'meal_type'), name='unique_soup_per_canteen_day'),
        ),
    ]
