# Generated by Django 6.0.4 on 2026-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_alter_productionorder_meal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('BREAKFAST', 'Snídaně'), ('SNACK_MORNING', 'Svačina dopolední'), ('SOUP', 'Polévka'), ('LUNCH', 'Oběd'), ('SNACK_AFTERNOON', 'Svačina odpolední'), ('DINNER', 'Večeře'), ('DINNER_SECOND', 'Druhá večeře')], db_index=True, default='LUNCH', help_text='Kategorie jídla (snídaně, svačina, polévka, oběd, večeře)', max_length=20, verbose_name='Typ jídla'),
        ),
    ]
