"""
Django settings for spiz_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Načtení .env dřív, než se sáhne na os.environ. Proměnné z prostředí
# (Docker, systemd) mají přednost před souborem, aby šlo nastavení přebít
# při nasazení. Chybí-li balíček nebo soubor, běží se jen s os.environ.
try:
    from dotenv import load_dotenv
except ImportError:
    pass
else:
    load_dotenv(Path(__file__).resolve().parent.parent / '.env', override=False)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-j4bbdmjl8!&7f@+o8j@+0#zn(ofs$^pgxelmto(@$#^ssm#=%l')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver')).split(',')

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'django_bootstrap5',

    # Moje aplikace
    'apps.core',
    'apps.inventory',
    'apps.production',
    'apps.canteens',
    'apps.reports',
    'apps.analytics',
    'apps.bufet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.core.middleware.ReadOnlyUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spiz_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.app_version',
                'apps.core.context_processors.active_users_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'spiz_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL všude - vývoj, testy i produkce. SQLite fallback tu schválně
# není: řádkové zámky (`select_for_update()`) neumí a tiše je ignoruje,
# takže by se testy lišily od provozu přesně v tom, na čem stojí správnost
# skladu. K vývoji stačí `docker compose up -d db`.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'spiz'),
        'USER': os.environ.get('POSTGRES_USER', 'spiz'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        # Bez znovupoužití spojení se na 1,5 OCPU pozná každý request -
        # navázání spojení k PG je dražší než otevření SQLite souboru.
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {'connect_timeout': 5},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'cs-CZ'

TIME_ZONE = 'Europe/Prague'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Formátování čísel - použití české lokalizace (čárka jako desetinný oddělovač)
USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = ' '

# Cesta k lokalizačním souborům
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Povolit formátování čísel ve formulářích
FORMAT_MODULE_PATH = [
    'spiz_project.formats',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Storage configuration (Django 6.0+ uses STORAGES instead of STATICFILES_STORAGE)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Nahrané soubory (skeny dodacích listů pro OCR import příjemek).
# V Dockeru musí MEDIA_ROOT ležet na perzistentním volume, jinak se skeny
# při redeployi ztratí.
MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media')))

# Mistral OCR pro načítání příjemek z fotky.
# Bez klíče je funkce nedostupná, zbytek aplikace běží normálně.
MISTRAL_API_KEY = os.environ.get('MISTRAL_API_KEY', '')
MISTRAL_OCR_MODEL = os.environ.get('MISTRAL_OCR_MODEL', 'mistral-ocr-latest')

# Jak dlouho se drží fotka dokladu, kterou nikdo nedopracoval do příjemky.
# Po potvrzení příjemky se sken maže hned, tohle je pojistka na rozdělané
# importy. Úklid provádí `manage.py purge_receipt_scans`, pouštěný z cronu.
OCR_SCAN_RETENTION_DAYS = int(os.environ.get('OCR_SCAN_RETENTION_DAYS', '7'))

# Zálohy databáze (pg_dump). Adresář leží v datovém volume a **mimo**
# MEDIA_ROOT i STATIC_ROOT - záloha obsahuje hashe hesel a data všech
# jídelen, takže ji nesmí servírovat whitenoise ani media.
DB_BACKUP_DIR = Path(os.environ.get('DB_BACKUP_DIR', str(BASE_DIR / 'data' / 'backups')))

# Vypínač stahování dumpu z /backup/. Nastavením na False jde přístup
# zavřít bez nasazení nové verze.
DB_DUMP_DOWNLOAD_ENABLED = os.environ.get('DB_DUMP_DOWNLOAD_ENABLED', 'True').lower() not in (
    'false', '0', 'no'
)

# Zabezpečení pro provoz za HTTPS.
#
# Vypínač je jeden a **výchozí hodnota je False schválně**: kdyby se tohle
# zapnulo na instalaci, která běží po HTTP, uživatelé by se okamžitě
# nepřihlásili (cookie by prohlížeč neposlal) a `SECURE_SSL_REDIRECT` by
# navíc udělal nekonečnou smyčku přesměrování. Zapněte HTTPS_ONLY=True až
# ve chvíli, kdy aplikace jede za HTTPS.
#
# Za reverzní proxy je podstatná i `SECURE_PROXY_SSL_HEADER`. Bez ní Django
# vidí spojení od proxy jako HTTP, znovu přesměruje na HTTPS a proxy pošle
# požadavek zpátky - smyčka. Proxy tedy musí posílat `X-Forwarded-Proto`.
#
# Proč to není kosmetika: přes /backup/ se stahuje kompletní dump databáze
# s hashi hesel a daty všech jídelen. Po HTTP by ho četl kdokoli na trase.
HTTPS_ONLY = os.environ.get('HTTPS_ONLY', 'False').lower() in ('true', '1', 'yes')

if HTTPS_ONLY:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Rok. HSTS je nevratné po dobu své platnosti - prohlížeč si zapamatuje,
    # že na tuhle doménu smí jen přes HTTPS, a zpátky to nejde odvolat jinak
    # než vypršením. Proto až po ověření, že HTTPS spolehlivě funguje.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Hlavní konfigurace Django projektu. Zde se registrují aplikace, databáze a další základní nastavení.

# Authentication redirects
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'

# Logging configuration
#
# Adresář se musí založit dřív, než ho logging dostane do ruky. `logs/` není
# v gitu ani v build kontextu image, takže v čerstvém klonu i v čerstvém
# kontejneru chybí - a `dictConfig` na chybějící cestě spadne rovnou při
# `django.setup()` hláškou "Unable to configure handler 'file'". Aplikace
# tedy vůbec nenaběhne a z hlášky není poznat, že jde jen o chybějící
# adresář.
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'audit.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'apps.inventory': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.production': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
