# Generated by Django 5.2.6 on 2025-09-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surovina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název suroviny')),
                ('aktualni_mnozstvi', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Aktuální množství')),
                ('jednotka', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Litr'), ('ks', 'Kus'), ('g', 'Gram')], default='kg', max_length=2, verbose_name='Jednotka')),
                ('prumerna_nakupni_cena', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Průměrná nákupní cena (za jednotku)')),
                ('posledni_aktualizace', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Surovina',
                'verbose_name_plural': 'Suroviny na skladě',
                'ordering': ['nazev'],
            },
        ),
    ]
