# Generated by Django 5.2.6 on 2025-09-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Název suroviny')),
                ('unit', models.CharField(max_length=10, verbose_name='Měrná jednotka')),
            ],
            options={
                'verbose_name': 'Surovina',
                'verbose_name_plural': 'Suroviny',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Název receptu')),
                ('description', models.TextField(blank=True, verbose_name='Postup přípravy')),
            ],
            options={
                'verbose_name': 'Recept',
                'verbose_name_plural': 'Recepty',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_adult', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Množství pro dospělou porci')),
                ('quantity_child', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Množství pro dětskou porci')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient', verbose_name='Surovina')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe', verbose_name='Recept')),
            ],
            options={
                'verbose_name': 'Norma receptu',
                'verbose_name_plural': 'Normy receptů',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='core.RecipeIngredient', to='core.ingredient', verbose_name='Suroviny'),
        ),
    ]
