# Generated by Django 4.2.25 on 2025-10-27 20:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kód kategorie')),
                ('name', models.CharField(max_length=100, verbose_name='Název kategorie')),
            ],
            options={
                'verbose_name': 'Kategorie receptu',
                'verbose_name_plural': 'Kategorie receptů',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity_adult',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity_child',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='base_unit',
            field=models.CharField(default='kg', help_text='Jednotka používaná na skladě (kg, l, ks)', max_length=10, verbose_name='Skladová jednotka'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=3, default=Decimal('1000'), help_text='Koeficient převodu z receptové na skladovou jednotku (např. 1000 pro g→kg)', max_digits=10, verbose_name='Konverzní faktor'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe_unit',
            field=models.CharField(default='g', help_text='Jednotka používaná v receptech (g, ml, ks)', max_length=10, verbose_name='Receptová jednotka'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='base_portions',
            field=models.PositiveIntegerField(default=10, help_text='Referenční počet porcí pro normu (obvykle 10)', verbose_name='Základní počet porcí'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='code',
            field=models.CharField(blank=True, help_text="Kód receptu z receptáře (např. '1', 'D3-6')", max_length=20, verbose_name='Kód receptu'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='notes',
            field=models.CharField(blank=True, help_text="Poznámky k surovině (např. 'dle potřeby', 'na osmažení')", max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_per_portion',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), help_text='Množství suroviny na 1 porci v receptových jednotkách (např. gramy)', max_digits=10, verbose_name='Množství na 1 porci'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Název receptu'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='core.category', verbose_name='Kategorie'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('category', 'code')},
        ),
    ]
