# Generated by Django 4.2.25 on 2025-10-28 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canteens', '0001_initial'),
        ('core', '0002_category_remove_recipeingredient_quantity_adult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredient_set', to='core.recipe', verbose_name='Recept'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canteens', models.ManyToManyField(blank=True, help_text='Jídelny, které může tento uživatel spravovat.', to='canteens.canteen', verbose_name='Přiřazené jídelny')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Uživatelský profil',
                'verbose_name_plural': 'Uživatelské profily',
            },
        ),
    ]
