# Generated by Django 4.2.24 on 2025-11-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_recipeingredient_recipe_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='core.category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='code',
            field=models.CharField(blank=True, help_text="Generuje se automaticky podle kategorie (např. 'PL-001', 'HJ-042')", max_length=20, verbose_name='Kód receptu'),
        ),
    ]
