# Generated by Django 6.0.1 on 2026-01-19 15:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_recipe_category_alter_recipe_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='selling_vat_rate',
            field=models.DecimalField(choices=[(Decimal('21'), '21%'), (Decimal('12'), '12%'), (Decimal('0'), '0%')], decimal_places=2, default=Decimal('12.00'), help_text='Výchozí DPH sazba pro tento recept (lze změnit při výrobě)', max_digits=5, verbose_name='Výchozí sazba DPH při prodeji (%)'),
        ),
    ]
