# Generated by Django 6.0.1 on 2026-01-23 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_selling_vat_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deaktivováno dne'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_ingredients', to=settings.AUTH_USER_MODEL, verbose_name='Deaktivoval'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Deaktivované suroviny se nezobrazují v seznamech, ale zůstávají v historických datech', verbose_name='Aktivní'),
        ),
    ]
