# Generated by Django 6.0.4 on 2026-05-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_soft_delete_to_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_readonly',
            field=models.BooleanField(default=False, help_text='Uživatel může data pouze prohlížet, nemůže je vytvářet, upravovat ani mazat.', verbose_name='Pouze čtení'),
        ),
    ]
