# Generated by Django 6.0.4 on 2026-07-06 08:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_is_readonly_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity_per_portion',
            field=models.DecimalField(decimal_places=3, help_text='Množství suroviny na 1 porci v receptových jednotkách (např. gramy)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Množství na 1 porci'),
        ),
    ]
