# Generated by Django 6.0.4 on 2026-07-06 08:53

import re
from collections import defaultdict

from django.db import migrations, models


def dedup_recipe_codes(apps, schema_editor):
    """Přečísluje globální duplicity kódů, aby prošel unique constraint.

    Kód byl dosud unikátní jen v rámci kategorie — stejný kód mohl
    existovat ve dvou kategoriích (typicky po přesunu receptu). První
    výskyt (nejnižší id) si kód nechá, další dostanou nejbližší volné
    číslo se svým prefixem.
    """
    Recipe = apps.get_model('core', 'Recipe')

    by_code = defaultdict(list)
    for recipe in Recipe.objects.exclude(code='').order_by('id'):
        by_code[recipe.code].append(recipe)

    existing = set(by_code.keys())
    for code, recipes in by_code.items():
        for recipe in recipes[1:]:
            match = re.match(r'^(.*-)(\d+)$', recipe.code)
            if match:
                prefix, number = match.group(1), int(match.group(2)) + 1
            else:
                prefix, number = f'{recipe.code}-', 1
            new_code = f'{prefix}{number:03d}'
            while new_code in existing:
                number += 1
                new_code = f'{prefix}{number:03d}'
            recipe.code = new_code
            recipe.save(update_fields=['code'])
            existing.add(new_code)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_recipeingredient_quantity_per_portion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
        migrations.RunPython(dedup_recipe_codes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='unique_recipe_code'),
        ),
    ]
