# Generated by Django 6.0.4 on 2026-07-08 21:51

import django.db.models.functions.comparison
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_recipe_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'czech')], 'verbose_name': 'Surovina', 'verbose_name_plural': 'Suroviny'},
        ),
    ]
