# Generated by Django 5.2.6 on 2025-09-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Název jídelny')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresa')),
            ],
            options={
                'verbose_name': 'Jídelna',
                'verbose_name_plural': 'Jídelny',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název skladu')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='canteens.canteen', verbose_name='Jídelna')),
            ],
            options={
                'verbose_name': 'Sklad',
                'verbose_name_plural': 'Sklady',
                'unique_together': {('name', 'canteen')},
            },
        ),
    ]
