# Generated by Django 6.0.1 on 2026-01-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Sklad je zamčen kvůli probíhající inventuře', verbose_name='Zamčeno'),
        ),
    ]
