# Generated by Django 6.0.1 on 2026-01-15 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0002_warehouse_is_locked'),
        ('inventory', '0009_inventoryverification_inventoryverificationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='locked_by_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventoryverification', verbose_name='Zamčeno inventurou'),
        ),
    ]
