# Generated by Django 6.0.1 on 2026-01-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0003_warehouse_locked_by_inventory'),
        ('inventory', '0010_stockitem_price_without_vat_stockitem_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_transit_warehouse',
            field=models.BooleanField(default=False, help_text='Tento sklad slouží jako mezisklad při převodech mezi sklady', verbose_name='Mezisklad pro převody'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_transit_warehouse', True)), fields=('canteen',), name='unique_transit_warehouse_per_canteen'),
        ),
    ]
