# Generated by Django 6.0.1 on 2026-01-21 11:01

from django.db import migrations


def create_transit_warehouses(apps, schema_editor):
    """
    Vytvoří mezisklad pro převody pro každou existující jídelnu.
    """
    Canteen = apps.get_model('canteens', 'Canteen')
    Warehouse = apps.get_model('canteens', 'Warehouse')
    
    for canteen in Canteen.objects.all():
        # Vytvoříme mezisklad pokud ještě neexistuje
        if not Warehouse.objects.filter(canteen=canteen, is_transit_warehouse=True).exists():
            Warehouse.objects.create(
                name=f'{canteen.name} - Převody',
                canteen=canteen,
                is_transit_warehouse=True,
                is_locked=False
            )


def reverse_transit_warehouses(apps, schema_editor):
    """
    Odstraní mezisklady vytvořené touto migrací.
    """
    Warehouse = apps.get_model('canteens', 'Warehouse')
    Warehouse.objects.filter(is_transit_warehouse=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0004_warehouse_is_transit_warehouse_and_more'),
    ]

    operations = [
        migrations.RunPython(create_transit_warehouses, reverse_transit_warehouses),
    ]
