# Generated by Django 5.2.6 on 2025-09-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canteens', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Množství na skladě')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nákupní cena za jednotku')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient', verbose_name='Surovina')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='canteens.warehouse', verbose_name='Sklad')),
            ],
            options={
                'verbose_name': 'Skladová položka',
                'verbose_name_plural': 'Skladové položky',
                'unique_together': {('ingredient', 'warehouse')},
            },
        ),
    ]
