# Generated by Django 4.2.25 on 2025-11-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='quantity_blocked',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Blokované množství'),
        ),
    ]
