# Generated by Django 5.2.6 on 2025-11-24 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0001_initial'),
        ('core', '0004_alter_recipe_category_alter_recipe_code'),
        ('inventory', '0002_add_quantity_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nákupní cena za jednotku')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Datum a čas od kdy platí tato cena', verbose_name='Platnost od')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.ingredient', verbose_name='Surovina')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='canteens.warehouse', verbose_name='Sklad')),
            ],
            options={
                'verbose_name': 'Historie ceny suroviny',
                'verbose_name_plural': 'Historie cen surovin',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['ingredient', 'warehouse', '-valid_from'], name='inventory_i_ingredi_14753a_idx')],
            },
        ),
    ]
