# Generated by Django 5.2.6 on 2025-11-24 15:46

from django.db import migrations
from django.utils import timezone


def populate_price_history_from_stock_items(apps, schema_editor):
    """
    Migruje existující ceny ze StockItem do IngredientPriceHistory.
    Pro každou skladovou položku vytvoří historický záznam s aktuální cenou.
    """
    StockItem = apps.get_model('inventory', 'StockItem')
    IngredientPriceHistory = apps.get_model('inventory', 'IngredientPriceHistory')
    
    # Projdeme všechny skladové položky a vytvoříme pro ně historické záznamy
    for stock_item in StockItem.objects.all():
        # Vytvoříme historický záznam pouze pokud ještě neexistuje
        if not IngredientPriceHistory.objects.filter(
            ingredient=stock_item.ingredient,
            warehouse=stock_item.warehouse
        ).exists():
            IngredientPriceHistory.objects.create(
                ingredient=stock_item.ingredient,
                warehouse=stock_item.warehouse,
                price=stock_item.price,
                valid_from=timezone.now()
            )


def reverse_populate(apps, schema_editor):
    """
    Reverze migrace - smaže všechny historické záznamy.
    """
    IngredientPriceHistory = apps.get_model('inventory', 'IngredientPriceHistory')
    IngredientPriceHistory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredientpricehistory'),
    ]

    operations = [
        migrations.RunPython(populate_price_history_from_stock_items, reverse_populate),
    ]
