# Generated by Django 5.2.6 on 2025-11-24 16:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0001_initial'),
        ('core', '0004_alter_recipe_category_alter_recipe_code'),
        ('inventory', '0004_populate_price_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Např. číslo dodacího listu nebo faktury', max_length=50, verbose_name='Číslo dokladu')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum příjmu')),
                ('supplier', models.CharField(blank=True, help_text='Název dodavatele', max_length=200, verbose_name='Dodavatel')),
                ('status', models.CharField(choices=[('DRAFT', 'Koncept'), ('CONFIRMED', 'Potvrzeno')], default='DRAFT', max_length=10, verbose_name='Stav')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámky')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Potvrzeno dne')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='canteens.warehouse', verbose_name='Sklad')),
            ],
            options={
                'verbose_name': 'Příjem zboží',
                'verbose_name_plural': 'Příjmy zboží',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Množství v základní jednotce suroviny', max_digits=10, verbose_name='Množství')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nákupní cena za jednotku')),
                ('notes', models.CharField(blank=True, help_text='Např. šarže, expirace', max_length=200, verbose_name='Poznámka')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.goodsreceipt', verbose_name='Příjem zboží')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ingredient', verbose_name='Surovina')),
            ],
            options={
                'verbose_name': 'Položka příjmu zboží',
                'verbose_name_plural': 'Položky příjmu zboží',
                'ordering': ['ingredient__name'],
            },
        ),
    ]
