# Generated by Django 6.0.1 on 2026-01-14 15:18

from decimal import Decimal
from django.db import migrations


def populate_vat_data(apps, schema_editor):
    """
    Populuje DPH data pro všechny existující GoodsReceiptItem záznamy.
    Předpokládá 21% DPH pro staré záznamy bez DPH informací.
    """
    GoodsReceiptItem = apps.get_model('inventory', 'GoodsReceiptItem')
    
    items_to_update = []
    for item in GoodsReceiptItem.objects.filter(price_without_vat__isnull=True):
        if item.price:
            # Výpočet ceny bez DPH z celkové ceny (předpoklad 21% DPH)
            item.price_without_vat = item.price / Decimal('1.21')
            item.vat_rate = Decimal('21')
            # Výpočet částky DPH
            item.vat_amount = item.price - item.price_without_vat
            items_to_update.append(item)
    
    # Hromadné uložení
    if items_to_update:
        GoodsReceiptItem.objects.bulk_update(
            items_to_update, 
            ['price_without_vat', 'vat_rate', 'vat_amount']
        )
        print(f"✓ Aktualizováno {len(items_to_update)} položek příjmu s DPH daty")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_vat_to_goods_receipt'),
    ]

    operations = [
        migrations.RunPython(populate_vat_data, reverse_code=migrations.RunPython.noop),
    ]
