# Generated by Django 6.0.1 on 2026-01-14 15:54

import django.db.models.deletion
from django.db import migrations, models


def populate_warehouse_from_goods_receipt(apps, schema_editor):
    """
    Nastaví warehouse u všech GoodsReceiptItem z jejich goods_receipt.warehouse
    """
    GoodsReceiptItem = apps.get_model('inventory', 'GoodsReceiptItem')
    
    items_to_update = []
    for item in GoodsReceiptItem.objects.select_related('goods_receipt').all():
        if not item.warehouse_id:  # Pouze pokud ještě není nastaveno
            item.warehouse = item.goods_receipt.warehouse
            items_to_update.append(item)
    
    if items_to_update:
        GoodsReceiptItem.objects.bulk_update(items_to_update, ['warehouse'])
        print(f"✓ Nastaveno warehouse u {len(items_to_update)} položek příjmu")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_populate_vat_fields'),
        ('canteens', '0001_initial'),
    ]

    operations = [
        # Krok 1: Přidat pole jako nullable (pokud neexistuje se přidá, pokud existuje neprovede se nic)
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='warehouse',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='canteens.warehouse',
                verbose_name='Sklad',
                help_text='Sklad, do kterého se surovina přijímá'
            ),
        ),
        # Krok 2: Populovat data ze goods_receipt.warehouse
        migrations.RunPython(
            populate_warehouse_from_goods_receipt,
            reverse_code=migrations.RunPython.noop
        ),
        # Krok 3: Změnit na NOT NULL
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='warehouse',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='canteens.warehouse',
                verbose_name='Sklad',
                help_text='Sklad, do kterého se surovina přijímá'
            ),
        ),
    ]
