# Generated by Django 6.0.1 on 2026-01-15 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0002_warehouse_is_locked'),
        ('core', '0004_alter_recipe_category_alter_recipe_code'),
        ('inventory', '0008_add_warehouse_to_receipt_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Koncept'), ('IN_PROGRESS', 'Probíhá'), ('COMPLETED', 'Dokončeno'), ('CANCELLED', 'Zrušeno')], default='DRAFT', max_length=20, verbose_name='Stav')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámky')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Zahájeno')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dokončeno')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Zrušeno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories_completed', to=settings.AUTH_USER_MODEL, verbose_name='Dokončil')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories_created', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories_started', to=settings.AUTH_USER_MODEL, verbose_name='Zahájil')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_verifications', to='canteens.warehouse', verbose_name='Sklad')),
            ],
            options={
                'verbose_name': 'Inventura',
                'verbose_name_plural': 'Inventury',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryVerificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Množství dle systému před inventurou', max_digits=10, verbose_name='Množství v evidenci')),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Skutečně nalezené množství při inventuře', max_digits=10, null=True, verbose_name='Spočítané množství')),
                ('difference', models.DecimalField(decimal_places=3, default=0, help_text='Rozdíl mezi spočítaným a systémovým množstvím', max_digits=10, verbose_name='Rozdíl')),
                ('is_newly_found', models.BooleanField(default=False, help_text='Surovina nebyla v evidenci, ale byla nalezena při inventuře', verbose_name='Nově nalezeno')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámka')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ingredient', verbose_name='Surovina')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryverification', verbose_name='Inventura')),
            ],
            options={
                'verbose_name': 'Položka inventury',
                'verbose_name_plural': 'Položky inventury',
                'ordering': ['ingredient__name'],
                'unique_together': {('verification', 'ingredient')},
            },
        ),
    ]
