# Generated by Django 6.0.1 on 2026-01-19 16:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryverification_inventoryverificationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='price_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena bez DPH'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='vat_rate',
            field=models.DecimalField(choices=[(Decimal('21'), '21%'), (Decimal('12'), '12%'), (Decimal('0'), '0%')], decimal_places=2, default=Decimal('12'), max_digits=5, verbose_name='Sazba DPH'),
        ),
    ]
