# Generated by Django 6.0.1 on 2026-01-21 11:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0004_warehouse_is_transit_warehouse_and_more'),
        ('core', '0005_recipe_selling_vat_rate'),
        ('inventory', '0010_stockitem_price_without_vat_stockitem_vat_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(help_text='Automaticky generované číslo převodky', max_length=50, unique=True, verbose_name='Číslo převodky')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum převodky')),
                ('status', models.CharField(choices=[('DRAFT', 'Návrh'), ('IN_TRANSIT', 'V převozu'), ('COMPLETED', 'Dokončeno'), ('CANCELLED', 'Zrušeno')], default='DRAFT', max_length=20, verbose_name='Stav')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Zahájeno')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dokončeno')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('warehouse_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='canteens.warehouse', verbose_name='Ze skladu')),
                ('warehouse_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='canteens.warehouse', verbose_name='Do skladu')),
            ],
            options={
                'verbose_name': 'Převodka',
                'verbose_name_plural': 'Převodky',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Množství')),
                ('unit_price_with_vat', models.DecimalField(decimal_places=2, help_text='Automaticky převzato ze zdrojového skladu', max_digits=10, verbose_name='Jednotková cena s DPH')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ingredient', verbose_name='Surovina')),
                ('stock_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer', verbose_name='Převodka')),
            ],
            options={
                'verbose_name': 'Položka převodky',
                'verbose_name_plural': 'Položky převodky',
                'ordering': ['ingredient__name'],
                'unique_together': {('stock_transfer', 'ingredient')},
            },
        ),
    ]
