# Generated by Django 6.0.1 on 2026-01-21 14:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_selling_vat_rate'),
        ('inventory', '0011_stocktransfer_stocktransferitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Název dodavatele')),
                ('slug', models.SlugField(help_text="Jednoznačný identifikátor pro API (např. 'zelinar', 'pekarna')", unique=True, verbose_name='Identifikátor')),
                ('is_active', models.BooleanField(default=True, help_text='Deaktivování skryje dodavatele ze šablon', verbose_name='Aktivní')),
                ('template_cache_key', models.CharField(blank=True, help_text='Auto-generovaný klíč pro cache', max_length=100, verbose_name='Cache klíč')),
            ],
            options={
                'verbose_name': 'Dodavatel',
                'verbose_name_plural': 'Dodavatelé',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.CharField(blank=True, help_text='Název dodavatele (pro postupnou migraci)', max_length=200, verbose_name='Dodavatel'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier_obj',
            field=models.ForeignKey(blank=True, help_text='Dodavatel s možností šablon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='inventory.supplier', verbose_name='Dodavatel (nový)'),
        ),
        migrations.CreateModel(
            name='SupplierIngredientTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price_without_vat', models.DecimalField(blank=True, decimal_places=2, help_text='Přednastavená cena bez DPH pro rychlejší vyplnění', max_digits=10, null=True, verbose_name='Výchozí cena bez DPH')),
                ('default_vat_rate', models.DecimalField(choices=[(Decimal('21'), '21%'), (Decimal('12'), '12%'), (Decimal('0'), '0%')], decimal_places=2, default=Decimal('12'), max_digits=5, verbose_name='Výchozí sazba DPH')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Pořadí zobrazení v šabloně (0 = první)', verbose_name='Pořadí')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient', verbose_name='Surovina')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_ingredients', to='inventory.supplier', verbose_name='Dodavatel')),
            ],
            options={
                'verbose_name': 'Šablona suroviny',
                'verbose_name_plural': 'Šablony surovin',
                'ordering': ['sort_order', 'ingredient__name'],
                'unique_together': {('supplier', 'ingredient')},
            },
        ),
    ]
