# Generated by Django 6.0.1 on 2026-01-21 14:12

from django.db import migrations
from decimal import Decimal


def create_default_suppliers(apps, schema_editor):
    """Vytvoření výchozích dodavatelů a jejich šablon surovin"""
    Supplier = apps.get_model('inventory', 'Supplier')
    SupplierIngredientTemplate = apps.get_model('inventory', 'SupplierIngredientTemplate')
    Ingredient = apps.get_model('core', 'Ingredient')
    
    # Vytvoření dodavatelů
    zelinar, created = Supplier.objects.get_or_create(
        slug='zelinar',
        defaults={
            'name': 'Zelinář',
            'template_cache_key': 'supplier_template_zelinar',
            'is_active': True
        }
    )
    
    pekarna, created = Supplier.objects.get_or_create(
        slug='pekarna',
        defaults={
            'name': 'Pekárna',
            'template_cache_key': 'supplier_template_pekarna',
            'is_active': True
        }
    )
    
    # Definice typických surovin pro Zelináře (ovoce a zelenina)
    zelinar_ingredients = [
        # Základní zelenina (12% DPH)
        ('Mrkev', Decimal('15.00'), Decimal('12'), 10),
        ('Celer', Decimal('20.00'), Decimal('12'), 20),
        ('Petržel', Decimal('25.00'), Decimal('12'), 30),
        ('Brokolice', Decimal('35.00'), Decimal('12'), 40),
        ('Paprika mix', Decimal('45.00'), Decimal('12'), 50),
        ('Cuketa', Decimal('30.00'), Decimal('12'), 60),
        ('Salát ledový', Decimal('18.00'), Decimal('12'), 70),
        ('Červená řepa vařená', Decimal('22.00'), Decimal('12'), 80),
        ('Kořenová zelenina', Decimal('16.00'), Decimal('12'), 90),
        ('Česnek', Decimal('80.00'), Decimal('12'), 100),
        ('Cibule', Decimal('12.00'), Decimal('12'), 110),
        
        # Ovoce (12% DPH)
        ('Jablka', Decimal('25.00'), Decimal('12'), 120),
        ('Banány', Decimal('28.00'), Decimal('12'), 130),
        ('Pomeranče', Decimal('30.00'), Decimal('12'), 140),
    ]
    
    # Definice typických surovin pro Pekárnu (pečivo)
    pekarna_ingredients = [
        # Pečivo (12% DPH)
        ('Rohlík bílý', Decimal('2.50'), Decimal('12'), 10),
        ('Kaiserka cereální', Decimal('3.00'), Decimal('12'), 20),
        ('Pečivo mix', Decimal('4.00'), Decimal('12'), 30),
        ('Bulka na hamburger', Decimal('5.00'), Decimal('12'), 40),
        ('Houskový knedlík', Decimal('8.00'), Decimal('12'), 50),
        
        # Základní suroviny pro pečení (12% DPH)
        ('Hladká mouka', Decimal('18.00'), Decimal('12'), 60),
        ('Droždí', Decimal('45.00'), Decimal('12'), 70),
    ]
    
    # Vytvoření šablon pro Zelináře
    for ingredient_name, price, vat_rate, sort_order in zelinar_ingredients:
        try:
            ingredient = Ingredient.objects.get(name__icontains=ingredient_name)
            SupplierIngredientTemplate.objects.get_or_create(
                supplier=zelinar,
                ingredient=ingredient,
                defaults={
                    'default_price_without_vat': price,
                    'default_vat_rate': vat_rate,
                    'sort_order': sort_order
                }
            )
        except Ingredient.DoesNotExist:
            # Pokud surovina neexistuje, vytvoříme ji
            print(f"Surovina '{ingredient_name}' neexistuje - přeskakuji")
            continue
        except Ingredient.MultipleObjectsReturned:
            # Pokud je více surovin s podobným názvem, vezmeme první
            ingredient = Ingredient.objects.filter(name__icontains=ingredient_name).first()
            if ingredient:
                SupplierIngredientTemplate.objects.get_or_create(
                    supplier=zelinar,
                    ingredient=ingredient,
                    defaults={
                        'default_price_without_vat': price,
                        'default_vat_rate': vat_rate,
                        'sort_order': sort_order
                    }
                )
    
    # Vytvoření šablon pro Pekárnu
    for ingredient_name, price, vat_rate, sort_order in pekarna_ingredients:
        try:
            ingredient = Ingredient.objects.get(name__icontains=ingredient_name)
            SupplierIngredientTemplate.objects.get_or_create(
                supplier=pekarna,
                ingredient=ingredient,
                defaults={
                    'default_price_without_vat': price,
                    'default_vat_rate': vat_rate,
                    'sort_order': sort_order
                }
            )
        except Ingredient.DoesNotExist:
            print(f"Surovina '{ingredient_name}' neexistuje - přeskakuji")
            continue
        except Ingredient.MultipleObjectsReturned:
            ingredient = Ingredient.objects.filter(name__icontains=ingredient_name).first()
            if ingredient:
                SupplierIngredientTemplate.objects.get_or_create(
                    supplier=pekarna,
                    ingredient=ingredient,
                    defaults={
                        'default_price_without_vat': price,
                        'default_vat_rate': vat_rate,
                        'sort_order': sort_order
                    }
                )
    
    print(f"Vytvořeni dodavatelé: {zelinar.name}, {pekarna.name}")
    print(f"Šablony Zelináře: {zelinar.template_ingredients.count()} surovin")
    print(f"Šablony Pekárny: {pekarna.template_ingredients.count()} surovin")


def reverse_create_default_suppliers(apps, schema_editor):
    """Smazání výchozích dodavatelů"""
    Supplier = apps.get_model('inventory', 'Supplier')
    
    # Smazání dodavatelů (kaskádově smaže i jejich šablony)
    Supplier.objects.filter(slug__in=['zelinar', 'pekarna']).delete()
    print("Smazáni výchozí dodavatelé")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_supplier_models'),
    ]

    operations = [
        migrations.RunPython(
            create_default_suppliers,
            reverse_create_default_suppliers
        ),
    ]
