# Generated by Django 6.0.1 on 2026-01-28 10:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0005_create_transit_warehouses'),
        ('core', '0006_add_soft_delete_to_ingredient'),
        ('inventory', '0013_create_default_suppliers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HYGIENE', 'Hygiena'), ('BUFFET', 'Bufet'), ('OTHER', 'Ostatní')], default='OTHER', max_length=20, verbose_name='Kategorie')),
                ('write_off_date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum odepisování')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámky')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('cash_register_import_id', models.CharField(blank=True, help_text='Unikátní ID záznamu z pokladního systému', max_length=100, null=True, unique=True, verbose_name='ID importu z kasy')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Importováno dne')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='canteens.warehouse', verbose_name='Sklad')),
            ],
            options={
                'verbose_name': 'Odepsání mimo recepty',
                'verbose_name_plural': 'Odepsání mimo recepty',
                'ordering': ['-write_off_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockWriteOffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Množství')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Automaticky převzato ze skladu v okamžiku odepisování', max_digits=10, verbose_name='Jednotková nákupní cena s DPH')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Vyplňte u položek prodávaných v bufetu', max_digits=10, null=True, verbose_name='Prodejní cena za jednotku s DPH')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Poznámka k položce')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ingredient', verbose_name='Surovina')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockwriteoff', verbose_name='Odepsání')),
            ],
            options={
                'verbose_name': 'Položka odepsání',
                'verbose_name_plural': 'Položky odepsání',
                'ordering': ['ingredient__name'],
                'unique_together': {('write_off', 'ingredient')},
            },
        ),
    ]
