# Generated by Django 6.0.1 on 2026-01-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_stockwriteoff_stockwriteoffitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockwriteoffitem',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='stockwriteoff',
            name='category',
            field=models.CharField(choices=[('HYGIENE', 'Hygiena'), ('OTHER', 'Ostatní')], default='OTHER', max_length=20, verbose_name='Kategorie'),
        ),
    ]
