# Generated by Django 6.0.1 on 2026-01-28 14:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_stockwriteoffitem_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='vat_rate',
            field=models.DecimalField(choices=[(Decimal('21'), '21%'), (Decimal('12'), '12%'), (Decimal('0'), '0%')], decimal_places=2, default=Decimal('12.00'), max_digits=5, verbose_name='Sazba DPH (%)'),
        ),
    ]
