# Generated by Django 6.0.1 on 2026-01-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_stockwriteoffitem_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockwriteoff',
            name='category',
            field=models.CharField(choices=[('HYGIENE', 'Hygiena'), ('OPERATIONAL_EMPLOYEES', 'Provozní - zaměstnanci'), ('EDUCATIONAL_EMPLOYEES', 'Výchovní zaměstnanci'), ('TEACHERS', 'Učitelky'), ('OTHER', 'Ostatní')], default='OTHER', max_length=25, verbose_name='Kategorie'),
        ),
    ]
