# Generated by Django 6.0.1 on 2026-01-30 10:13

from django.db import migrations, models


def set_supplier_defaults(apps, schema_editor):
    """Nastavení výchozích ikon a barev pro existující dodavatele"""
    Supplier = apps.get_model('inventory', 'Supplier')
    
    # Definice výchozích hodnot pro dodavatele podle slugu
    supplier_defaults = {
        'zelinar': {
            'icon_class': 'fa-carrot',
            'button_color': 'outline-success'
        },
        'pekarna': {
            'icon_class': 'fa-bread-slice',
            'button_color': 'outline-warning'
        }
    }
    
    # Aktualizace existujících dodavatelů
    for slug, defaults in supplier_defaults.items():
        Supplier.objects.filter(slug=slug).update(**defaults)





class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_stockwriteoff_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='button_color',
            field=models.CharField(choices=[('primary', 'Modrá (primary)'), ('secondary', 'Šedá (secondary)'), ('success', 'Zelená (success)'), ('danger', 'Červená (danger)'), ('warning', 'Oranžová (warning)'), ('info', 'Tyrkysová (info)'), ('light', 'Světlá (light)'), ('dark', 'Tmavá (dark)'), ('outline-primary', 'Obrys modrá'), ('outline-success', 'Obrys zelená'), ('outline-warning', 'Obrys oranžová'), ('outline-info', 'Obrys tyrkysová')], default='outline-primary', help_text='Barva tlačítka v rychlých šablonách', max_length=30, verbose_name='Barva tlačítka'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='icon_class',
            field=models.CharField(default='fa-box', help_text="Font Awesome ikona (např. 'fa-carrot', 'fa-bread-slice', 'fa-box'). Seznam ikon: https://fontawesome.com/icons", max_length=100, verbose_name='Ikona'),
        ),
        migrations.RunPython(
            set_supplier_defaults,
            migrations.RunPython.noop
        ),
    ]
