# Generated by Django 6.0.1 on 2026-04-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_supplier_button_color_supplier_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockwriteoff',
            name='document_number',
            field=models.CharField(blank=True, help_text='Číslo dokladu pro evidenci', max_length=50, verbose_name='Číslo dokladu'),
        ),
    ]
