# Generated by Django 6.0.4 on 2026-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_populate_document_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockwriteoff',
            name='category',
            field=models.CharField(choices=[('CLEANING', 'Úklid'), ('MAINTENANCE', 'Údržba'), ('LAUNDRY', 'Prádelna'), ('STAFF_RS', 'Personál RS'), ('EDUCATIONAL_STAFF', 'Výchovný personál'), ('TEACHERS', 'Pedagogové'), ('ACCOMMODATION', 'Ubytovací akce'), ('OTHER', 'Ostatní')], default='OTHER', max_length=25, verbose_name='Kategorie'),
        ),
    ]
