# Generated by Django 6.0.4 on 2026-05-04 09:25

from django.db import migrations


CATEGORY_MAPPING = {
    'HYGIENE': 'CLEANING',
    'OPERATIONAL_EMPLOYEES': 'STAFF_RS',
    'EDUCATIONAL_EMPLOYEES': 'EDUCATIONAL_STAFF',
}


def remap_categories(apps, schema_editor):
    StockWriteOff = apps.get_model('inventory', 'StockWriteOff')
    for old_value, new_value in CATEGORY_MAPPING.items():
        StockWriteOff.objects.filter(category=old_value).update(category=new_value)


def reverse_remap_categories(apps, schema_editor):
    StockWriteOff = apps.get_model('inventory', 'StockWriteOff')
    for old_value, new_value in CATEGORY_MAPPING.items():
        StockWriteOff.objects.filter(category=new_value).update(category=old_value)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_update_writeoff_categories'),
    ]

    operations = [
        migrations.RunPython(remap_categories, reverse_remap_categories),
    ]
