# Generated by Django 6.0.4 on 2026-07-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remap_writeoff_categories_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockwriteoff',
            name='category',
            field=models.CharField(choices=[('CLEANING', 'Úklid'), ('MAINTENANCE', 'Údržba'), ('LAUNDRY', 'Prádelna'), ('STAFF_RS', 'Personál RS'), ('EDUCATIONAL_STAFF', 'Výchovný personál'), ('TEACHERS', 'Pedagogové'), ('ACCOMMODATION', 'Ubytovací akce'), ('BUFET_SALE', 'Bufet – prodej'), ('OTHER', 'Ostatní')], default='OTHER', max_length=25, verbose_name='Kategorie'),
        ),
    ]
