# Generated by Django 6.0.4 on 2026-07-08 20:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_stockwriteoff_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransferitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Množství'),
        ),
    ]
