# Generated by Django 6.0.4 on 2026-09-02 12:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ingredient_options'),
        ('inventory', '0023_alter_stocktransferitem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='ico',
            field=models.CharField(blank=True, help_text='Slouží k rozpoznání dodavatele na naskenovaném dokladu. Název se na dokladech píše pokaždé jinak, IČO ne.', max_length=8, null=True, unique=True, verbose_name='IČO'),
        ),
        migrations.CreateModel(
            name='GoodsReceiptScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, help_text='Relativně k MEDIA_ROOT. Prázdné, když už byl sken smazán.', max_length=255, verbose_name='Cesta k souboru')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Původní název souboru')),
                ('annotation', models.JSONField(blank=True, default=dict, help_text='Syrový výstup OCR, uchováváme kvůli dohledatelnosti', verbose_name='Rozpoznaná data')),
                ('markdown', models.TextField(blank=True, help_text='Text dokladu tak, jak ho OCR přečetlo', verbose_name='Přepis dokladu')),
                ('ocr_model', models.CharField(blank=True, max_length=100, verbose_name='Model OCR')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Nahráno')),
                ('file_deleted_at', models.DateTimeField(blank=True, help_text='Kdy byla fotka smazána. Anotace zůstává.', null=True, verbose_name='Soubor smazán')),
                ('goods_receipt', models.OneToOneField(blank=True, help_text='Prázdné, dokud uživatel import nedokončil', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='inventory.goodsreceipt', verbose_name='Příjemka')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nahrál')),
            ],
            options={
                'verbose_name': 'Sken dokladu',
                'verbose_name_plural': 'Skeny dokladů',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierItemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(help_text='Přesně tak, jak název přišel z dokladu', max_length=255, verbose_name='Název na dokladu')),
                ('raw_key', models.CharField(db_index=True, max_length=255, verbose_name='Klíč pro přesnou shodu')),
                ('core_key', models.CharField(db_index=True, max_length=255, verbose_name='Klíč pro přihrádku')),
                ('is_ignored', models.BooleanField(default=False, help_text='Řádek se při importu přeskočí (zaokrouhlení, doprava, obaly)', verbose_name='Nezbožní řádek')),
                ('unit', models.CharField(blank=True, help_text='Jednotka, ve které dodavatel položku fakturuje', max_length=10, verbose_name='Jednotka na dokladu')),
                ('unit_factor', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Kolika skladovými jednotkami je jedna jednotka z dokladu. Karton dvanácti kusů = 12, jinak 1.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Přepočet na skladovou jednotku')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Počet použití')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Naposledy použito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_aliases', to='core.ingredient', verbose_name='Surovina')),
                ('supplier', models.ForeignKey(blank=True, help_text='Prázdné = alias platí pro všechny dodavatele', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_aliases', to='inventory.supplier', verbose_name='Dodavatel')),
            ],
            options={
                'verbose_name': 'Alias položky dodavatele',
                'verbose_name_plural': 'Aliasy položek dodavatelů',
                'ordering': ['supplier__name', 'raw_name'],
                'indexes': [models.Index(fields=['supplier', 'core_key'], name='inventory_s_supplie_064e6b_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'raw_key'), name='unique_alias_per_supplier'), models.UniqueConstraint(condition=models.Q(('supplier__isnull', True)), fields=('raw_key',), name='unique_global_alias')],
            },
        ),
    ]
