# Generated by Django 6.0.4 on 2026-09-02 13:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_supplier_ico_goodsreceiptscan_supplieritemalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='source_name',
            field=models.CharField(blank=True, help_text='Název položky tak, jak stál na dokladu – podle něj se učí aliasy', max_length=255, verbose_name='Název na dokladu'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='source_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Množství tak, jak stálo na dokladu, před přepočtem', max_digits=10, null=True, verbose_name='Množství na dokladu'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='source_unit',
            field=models.CharField(blank=True, help_text='Prázdné u ručně zadaných položek – ty jsou rovnou ve skladové jednotce', max_length=10, verbose_name='Jednotka na dokladu'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='unit_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Kolika skladovými jednotkami je jedna jednotka z dokladu', max_digits=10, verbose_name='Použitý přepočet'),
        ),
    ]
