# Generated by Django 6.0.4 on 2026-09-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_goodsreceiptitem_source_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Nákupní cena za jednotku (vč. DPH)'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='price_without_vat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Cena bez DPH za jednotku'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Částka DPH za jednotku'),
        ),
        migrations.AlterField(
            model_name='ingredientpricehistory',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Nákupní cena za jednotku'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Nákupní cena za jednotku'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='price_without_vat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Cena bez DPH'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='unit_price_with_vat',
            field=models.DecimalField(decimal_places=6, help_text='Automaticky převzato ze zdrojového skladu', max_digits=12, verbose_name='Jednotková cena s DPH'),
        ),
        migrations.AlterField(
            model_name='stockwriteoffitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, help_text='Automaticky převzato ze skladu v okamžiku odepisování', max_digits=12, verbose_name='Jednotková nákupní cena s DPH'),
        ),
        migrations.AlterField(
            model_name='supplieringredienttemplate',
            name='default_price_without_vat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Přednastavená cena bez DPH pro rychlejší vyplnění', max_digits=12, null=True, verbose_name='Výchozí cena bez DPH'),
        ),
    ]
