# Generated by Django 6.0.4 on 2026-09-03 12:38

from decimal import Decimal

from django.db import migrations, models


def prenest_stary_priznak(apps, schema_editor):
    """
    Dosud „poměr určen" znamenalo `unit_factor != 1`. Ten význam se přenese
    do nového příznaku, jinak by se doklady a aliasy s dřív zadaným
    přepočtem po nasazení znovu rozsvítily jako nevyřešené.

    Řádky s poměrem 1 zůstávají `False` – u nich se opravdu nedá poznat,
    jestli šlo o rozhodnutí, nebo o výchozí hodnotu. Radši se zeptat znovu
    než naskladnit 1:1 něco, co nikdo nepotvrdil.
    """
    for model in ('GoodsReceiptItem', 'SupplierItemAlias'):
        apps.get_model('inventory', model).objects.exclude(
            unit_factor=Decimal('1')
        ).update(unit_resolved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_goodsreceiptitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='unit_resolved',
            field=models.BooleanField(default=False, help_text='Poměr už někdo určil. Samotný `unit_factor` to neprozradí – jednička je zároveň výchozí hodnota i platný přepočet (1 balení = 1 kus).', verbose_name='Přepočet vyřešen'),
        ),
        migrations.AddField(
            model_name='supplieritemalias',
            name='unit_resolved',
            field=models.BooleanField(default=False, help_text='Poměr zadal uživatel, ne odhad. Odlišuje vědomé „1 bal = 1 ks" od výchozí jedničky, která znamená „nikdo neurčil".', verbose_name='Přepočet potvrzen člověkem'),
        ),
        migrations.RunPython(
            prenest_stary_priznak, migrations.RunPython.noop,
        ),
    ]
